# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='Yorum')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
            },
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Gorevler', 'verbose_name_plural': 'Gorev'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[(0, 'Devam ediyor'), (1, 'Bitti'), (2, 'Ertelendi')], default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks'),
        ),
    ]
