# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 06:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20161014_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
