# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='done_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Bitis Tarihi'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='plan_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Planlanan Tarih'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='note',
            field=models.CharField(max_length=500, verbose_name='Gorev'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[(0, 'Devam ediyor'), (1, 'Bitti'), (2, 'Ertelendi'), (3, 'Yarin yapilacak')], default=0, verbose_name='durum'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanici'),
        ),
    ]
