# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 09:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20161017_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='plan_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 17, 12, 32, 31, 608461), null=True, verbose_name='Planlanan Tarih'),
        ),
    ]
