# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20161018_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='done_date',
            field=models.DateTimeField(auto_now=True, verbose_name='En son degisen Tarih'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanici'),
        ),
    ]
