# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20161022_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='done_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Bitis Tarihi'),
        ),
    ]
