# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20161024_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'G\xf6revler', 'verbose_name_plural': 'G\xf6rev'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Olu\u015fturma Tarihi'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='done_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Degi\u015ftirilen Tarih'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='note',
            field=models.CharField(max_length=500, verbose_name='G\xf6rev'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[(0, 'Devam ediyor'), (1, 'Bitti'), (2, 'Ertelendi'), (3, 'Yar\u0131n Yap\u0131lacak')], default=0, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullan\u0131c\u0131'),
        ),
    ]
