# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20161024_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='plan_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Planlanan Tarih'),
        ),
    ]
