# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20161029_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='done_date',
            field=models.DateField(auto_now=True, verbose_name='Son Degi\u015ftirilen Tarih'),
        ),
    ]
