# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20161029_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Olu\u015fturma Tarihi'),
        ),
    ]
