# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20161029_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'G\xf6rev', 'verbose_name_plural': 'G\xf6revler'},
        ),
    ]
